"""Canonical registry of Garmin fields used by v2 metrics.

Source of truth for docs/v2/garmin-field-mapping.md. endpoint is one of:
activity_list | activity_details | lt | race_predictions | training_status |
user_settings | heart_rate_zones | daily_summary
"""

from dataclasses import dataclass

METRICS = frozenset(
    {
        "volume",
        "elevation",
        "trimp_edwards",
        "trimp_banister",
        "ctl",
        "atl",
        "tsb",
        "acwr",
        "decoupling",
        "vo2max",
        "lt_hr",
        "lt_pace",
        "cs_approx",
        "race_5k",
        "race_10k",
        "race_half",
        "race_full",
        "load_reference",
        "cross_training",
    }
)


@dataclass(frozen=True)
class GarminField:
    name: str
    endpoint: str
    units: str
    description: str
    metrics: tuple[str, ...]
    limitations: str = ""


ZONE_LIMIT = (
    "Seconds-in-zone buckets depend on the device HR-zone config. "
    "Reproducibility requires persisting RunnerProfile.hr_zones alongside the series."
)

FIELD_REGISTRY = (
    # ---- activity list (activitylist-service/activities/search/activities) ----
    GarminField("activityId", "activity_list", "id", "Per-activity unique integer id", ("volume",)),
    GarminField("activityUUID", "activity_list", "uuid", "Per-activity unique uuid", ("volume",)),
    GarminField(
        "activityType.typeKey",
        "activity_list",
        "enum",
        "Nested sport key (running, treadmill_running, indoor_cycling, strength_training, ...)",
        ("volume", "cross_training"),
        "Nested under 'activityType'; absent typeKey means classification falls back to sportTypeId.",
    ),
    GarminField(
        "sportTypeId",
        "activity_list",
        "id",
        "Numeric sport type id",
        ("volume", "cross_training"),
        "Backup for classification when typeKey is missing; mapping table maintained in normalize.py.",
    ),
    GarminField(
        "startTimeLocal",
        "activity_list",
        "ISO datetime",
        "Local wall-clock start (YYYY-MM-DD HH:MM:SS)",
        ("volume",),
        "Drives local calendar day/week bucketing. Timezone id recorded separately in timeZoneId.",
    ),
    GarminField("beginTimestamp", "activity_list", "epoch ms", "UTC start timestamp", ("volume",)),
    GarminField(
        "distance",
        "activity_list",
        "m",
        "Total distance",
        ("volume", "elevation"),
        "0.0 for indoor_cycling; absent for strength. Convert to km for human-facing series.",
    ),
    GarminField(
        "duration",
        "activity_list",
        "s",
        "Moving duration (excludes paused time)",
        ("volume", "trimp_banister", "trimp_edwards", "acwr"),
        "Use duration not elapsedDuration for TRIMP denominators; elapsedDuration adds pause time.",
    ),
    GarminField(
        "elapsedDuration",
        "activity_list",
        "s",
        "Elapsed wall-clock duration",
        ("volume",),
        "Can materially exceed duration on stop-and-go sessions; used for decoupling eligibility (>=90 min sustained).",
    ),
    GarminField(
        "movingDuration",
        "activity_list",
        "s",
        "Duration with motion",
        ("volume",),
        "Not always present; fall back to duration.",
    ),
    GarminField(
        "averageHR",
        "activity_list",
        "bpm",
        "Session mean heart rate",
        ("trimp_banister", "cross_training"),
        "Optional-sensor dependent (chest strap preferred). Missing on manually-uploaded strength data -> activity excluded from HR-based load.",
    ),
    GarminField(
        "maxHR",
        "activity_list",
        "bpm",
        "Session max heart rate",
        ("trimp_banister",),
        "Reported even when elevation is missing; excluded from inference when spikes look sensor-artifactual (not enforced in v2).",
    ),
    GarminField(
        "hrTimeInZone_1",
        "activity_list",
        "s",
        "Seconds in HR zone 1",
        ("trimp_edwards",),
        ZONE_LIMIT,
    ),
    GarminField(
        "hrTimeInZone_2",
        "activity_list",
        "s",
        "Seconds in HR zone 2",
        ("trimp_edwards",),
        ZONE_LIMIT,
    ),
    GarminField(
        "hrTimeInZone_3",
        "activity_list",
        "s",
        "Seconds in HR zone 3",
        ("trimp_edwards",),
        ZONE_LIMIT,
    ),
    GarminField(
        "hrTimeInZone_4",
        "activity_list",
        "s",
        "Seconds in HR zone 4",
        ("trimp_edwards",),
        ZONE_LIMIT,
    ),
    GarminField(
        "hrTimeInZone_5",
        "activity_list",
        "s",
        "Seconds in HR zone 5",
        ("trimp_edwards",),
        ZONE_LIMIT,
    ),
    GarminField(
        "averageSpeed",
        "activity_list",
        "m/s",
        "Mean moving speed",
        ("cs_approx",),
        "Not present on all activities; convert to min/km for humans.",
    ),
    GarminField(
        "fastestSplit_1609",
        "activity_list",
        "s",
        "Fastest 1-mile split within the session",
        ("cs_approx",),
        "Approximation only: not a controlled critical-speed test; best used as a lower-bound trend signal.",
    ),
    GarminField(
        "maxSpeed",
        "activity_list",
        "m/s",
        "Peak instantaneous speed",
        ("cs_approx",),
        "Sprint artifacts; not used directly for CS.",
    ),
    GarminField(
        "elevationGain",
        "activity_list",
        "m",
        "Total ascent",
        ("elevation", "decoupling"),
        "Absent on treadmill/intensity/indoor activities. Used as a gradient filter for decoupling (25 m/km).",
    ),
    GarminField(
        "elevationLoss",
        "activity_list",
        "m",
        "Total descent",
        ("elevation",),
        "Same indoor gap as elevationGain.",
    ),
    GarminField("minElevation", "activity_list", "m", "Lowest point", ("elevation",)),
    GarminField("maxElevation", "activity_list", "m", "Highest point", ("elevation",)),
    GarminField("avgElevation", "activity_list", "m", "Mean altitude", ("elevation",)),
    GarminField(
        "vO2MaxValue",
        "activity_list",
        "mL/kg/min",
        "Firstbeat VO2max estimate published for the run",
        ("vo2max",),
        "Only present on outdoor running (absent: treadmill, cross-training). Estimate (5-10% error), HRmax-dependent, underestimates highly-trained runners. Do not recompute.",
    ),
    GarminField(
        "aerobicTrainingEffect",
        "activity_list",
        "1-5",
        "Firstbeat aerobic TE",
        ("load_reference",),
        "Proprietary; reference only, never a gate.",
    ),
    GarminField(
        "anaerobicTrainingEffect",
        "activity_list",
        "1-5",
        "Firstbeat anaerobic TE",
        ("load_reference",),
        "Proprietary; reference only.",
    ),
    GarminField(
        "averageRunningCadenceInStepsPerMinute",
        "activity_list",
        "spm",
        "Mean cadence (running activities)",
        ("cs_approx",),
        "Running only; cadence is not used as a headline metric in v2.",
    ),
    GarminField(
        "avgStrideLength",
        "activity_list",
        "cm",
        "Mean stride length",
        ("cs_approx",),
        "Running only; informational.",
    ),
    GarminField(
        "startLatitude",
        "activity_list",
        "deg",
        "Start latitude",
        ("decoupling",),
        "Used for route clustering; horizontal geolocation (not fixed) required.",
    ),
    GarminField("startLongitude", "activity_list", "deg", "Start longitude", ("decoupling",), ""),
    GarminField("endLatitude", "activity_list", "deg", "End latitude", ("decoupling",), ""),
    GarminField("endLongitude", "activity_list", "deg", "End longitude", ("decoupling",), ""),
    GarminField(
        "locationName",
        "activity_list",
        "text",
        "Garmin-assigned place label",
        ("decoupling",),
        "Unreliable (frequently empty); route_key prefers start coordinates.",
    ),
    GarminField(
        "deviceId",
        "activity_list",
        "id",
        "Recording device id",
        ("decoupling",),
        "Proxy for sensor source. Cannot reliably distinguish chest strap vs optical from the list payload; flag recorded, honesty preferred.",
    ),
    GarminField(
        "manufacturer", "activity_list", "text", "Device manufacturer", ("decoupling",), ""
    ),
    GarminField(
        "calories",
        "activity_list",
        "kcal",
        "Estimated energy",
        ("cross_training",),
        "Estimate only; not a training-stress metric in v2.",
    ),
    GarminField(
        "hasIntensityIntervals",
        "activity_list",
        "bool",
        "Whether the session contains structured intervals",
        ("trimp_banister", "decoupling"),
        "Interval sessions are excluded from decoupling (not sustained effort); Banister TRIMP uses details HR series when available to handle them.",
    ),
    GarminField(
        "lapCount",
        "activity_list",
        "count",
        "Number of laps",
        ("volume",),
        "Informational / structure.",
    ),
    GarminField(
        "splitSummaries",
        "activity_list",
        "list",
        "Per-split-type aggregates (RWD_RUN etc.)",
        ("cs_approx", "decoupling"),
        "No per-split HR here — HR comes from activity_details.",
    ),
    # ---- activity details (activity-service/{id}/details) ----
    GarminField(
        "activityDetailMetrics[].metrics[directHeartRate]",
        "activity_details",
        "bpm[]",
        "Per-sample HR series (column located via metricDescriptors)",
        ("trimp_banister", "decoupling"),
        "One request per activity (rate-limit aware). Downsampled by maxChartSize; irregular ~1-7 s spacing with directTimestamp per sample; gaps possible when optical. Values arrive pre-scaled.",
    ),
    GarminField(
        "activityDetailMetrics[].metrics[directSpeed]",
        "activity_details",
        "m/s[]",
        "Per-sample speed series (column located via metricDescriptors)",
        ("decoupling", "cs_approx"),
        "Speed vs distance series can misalign on GPS dropouts; samples are irregularly spaced, use directTimestamp rather than assuming 1 Hz.",
    ),
    GarminField(
        "metrics[].distance",
        "activity_details",
        "m[]",
        "Cumulative distance series",
        ("cs_approx",),
    ),
    GarminField(
        "metrics[].altitude",
        "activity_details",
        "m[]",
        "Altitude series",
        ("elevation",),
        "Baro vs GPS-derived altitude varies; not used for headline elevation (activity list elevationGain is authoritative).",
    ),
    GarminField(
        "metrics[].wkt",
        "activity_details",
        "enum[]",
        "Per-sample workout step",
        ("decoupling",),
        "Use to mask non-effort segments when splitting halves.",
    ),
    GarminField(
        "lapsSummary",
        "activity_details",
        "list",
        "Per-lap summaries",
        ("decoupling", "trimp_banister"),
        "Fallback to lap-level HR if per-second series is empty.",
    ),
    # ---- performance endpoints ----
    GarminField(
        "speed_and_heart_rate.heartRate",
        "lt",
        "bpm",
        "Lactate-threshold HR",
        ("lt_hr",),
        "Anchored metric: LABEL trustworthy (7% error), pace is not (up to 20-26% overest.). Manual lab/race set via RunnerProfile.lthr_manual overrides.",
    ),
    GarminField(
        "speed_and_heart_rate.speed",
        "lt",
        "m/s",
        "Lactate-threshold speed",
        ("lt_pace", "cs_approx"),
        "FLAGGED: 2025 studies show Garmin LT pace can overestimate by 20-26%; use for trend, not absolute prescription.",
    ),
    GarminField(
        "speed_and_heart_rate.calendarDate",
        "lt",
        "date",
        "When LT was computed",
        ("lt_hr", "lt_pace"),
        "",
    ),
    GarminField(
        "Run_5k.time",
        "race_predictions",
        "ms",
        "Predicted 5k time",
        ("race_5k",),
        "Riegel-derived; trusted more than marathon. Unit is milliseconds in Garmin payload (reconciled in Task 12).",
    ),
    GarminField("Run_10k.time", "race_predictions", "ms", "Predicted 10k time", ("race_10k",), ""),
    GarminField(
        "Run_half_marathon.time",
        "race_predictions",
        "ms",
        "Predicted half time",
        ("race_half",),
        "Riegel calibration still OK at half distance.",
    ),
    GarminField(
        "Run_full_marathon.time",
        "race_predictions",
        "ms",
        "Predicted marathon time",
        ("race_full",),
        "LEAST TRUSTWORTHY: Riegel underestimates marathon by >=10 min for ~half of runners (Vickers 2016). Trend only.",
    ),
    GarminField(
        "load",
        "training_status",
        "arbitrary",
        "Firstbeat training load",
        ("load_reference",),
        "Proprietary, not independently validated. Reference display only.",
    ),
    GarminField(
        "trainingStatus",
        "training_status",
        "enum",
        "Productive/Maintaining/Detraining/Peaking/Recovery/Overreaching",
        ("load_reference",),
        "Proprietary, context only.",
    ),
    # ---- user profile / settings ----
    GarminField(
        "userData.maxHRSetting",
        "user_settings",
        "bpm",
        "Configured HRmax",
        ("trimp_banister", "vo2max"),
        "If unset, age-predicted fallback (220-age) used and flagged in metric flags.",
    ),
    GarminField(
        "userData.birthDate",
        "user_settings",
        "date",
        "Birth date",
        ("trimp_banister",),
        "Used for fallback HRmax and Banister sex exponent.",
    ),
    GarminField(
        "userData.measurementSystem",
        "user_settings",
        "enum",
        "statute|metric",
        ("volume",),
        "Documented; values stored in SI regardless.",
    ),
    GarminField(
        "heartRateZones",
        "heart_rate_zones",
        "list",
        "Configured HR zone thresholds",
        ("trimp_edwards",),
        "ZONE_LIMIT: zone-second buckets are only reproducible if the same zone thresholds are stored. Persist in RunnerProfile.hr_zones.",
    ),
)


def fields_for_metric(metric: str) -> tuple[GarminField, ...]:
    return tuple(f for f in FIELD_REGISTRY if metric in f.metrics)
